### ISSUE TITLE
Can't upgrade the tinymce version inside the plugin

### ISSUE THREAD

**Issue by andreasthulin** [mvdkleijn/tinymce#3]
Hi! First of all, thanks for a very nice plugin to a great CMS! :+1: 

I installed the tinymce plugin and somewhere read that I would be able to upgrade tinymce inside the plugin just by replacing it with a new stock version. I just did that using version 4.1.9 (http://download.moxiecode.com/tinymce/tinymce_4.1.9.zip) but unfortunately the plugin broke.

Any ideas on how to sort this out would be highly appreciated.

BR
Andreas Thulin

**Comment by mvdkleijn** [comment]
I'll have to take a look. I've not worked on the plugin in quite some time and lots may have changed with TinyMCE itself, breaking the integration.

**Comment by andreasthulin** [comment]
All right, thanks! I completely understand if you don't have the time,
though. :)

BR
Andreas

2015-04-18 22:18 GMT+02:00 Martijn <notifications@github.com>:

**Comment by benutti** [comment]
any news on this subject?
